### PR TITLE
Archer Arrows

### PR DESCRIPTION
**Pull request by Bobthe28th**
- [X] Poison Arrow
- [X] Sonic Arrow
- [X] Ghost Arrow
- [x] just like normal arrows

### CODE REVIEW

**Comment by Tman2143** [comment]
well no clip was the only cool one we had in mind, maybe we can make tracking arrow better this time?

**Comment by Tman2143** [comment]
also poison arrow and maybe weakness arrow

**Comment by Bobthe28th** [comment]
> well no clip was the only cool one we had in mind, maybe we can make tracking arrow better this time?

No clip is possible if I just use particles, kinda like the wizard zap but with travel time

**Comment by Tman2143** [comment]
sonic arrow?

**Comment by Bobthe28th** [comment]
like hanzo arrow

**Comment by Tman2143** [comment]
glowing system?

**Comment by Bobthe28th** [comment]
for sonic arrow i had to redo glowing system

**Comment by Bobthe28th** [comment]
I dont want the stop glowing from capturing the flag to also stop glowing from sonic arrow so I had to make system

**Comment by Bobthe28th** [comment]
What are other arrows
also
> No clip is possible if I just use particles, kinda like the wizard zap but with travel time

**Comment by Tman2143** [comment]
should sonic arrow make particular so people know it's there?

**Comment by Bobthe28th** [comment]
> should sonic arrow make particles so people know it's there?

It makes particles when it is flying but should it when it is on the ground? what should the particle be? I have it so when it lands it makes people around it glow then stop glowing in x seconds, it doesn't linger

**Comment by Bobthe28th** [comment]
I also made glow effect show in top right

**Comment by Tman2143** [comment]
it should emit particles like hanzos arrow does when it's on the ground

**Comment by Bobthe28th** [comment]
> it should emit particles like hanzos arrow does when it's on the ground

It only sends one impulse when it lands, people within x radius will glow for x seconds. It doesn't matter if people know where it is because they can't do anything to stop it

**Comment by Bobthe28th** [comment]
@Tman2143 any other arrows?
Also what are cooldowns/amounts?

**Comment by Tman2143** [comment]
no other arrows and i'm gonna need to be in the game to decide the cooldowns

**Comment by Bobthe28th** [comment]
> no other arrows and i'm gonna need to be in the game to decide the cooldowns

Ok ill just merge, we can make pull request later to change cooldowns

**Pull request merged**
