### PR TITLE
Flag on head

### PR DESCRIPTION
**Pull request by Bobthe28th**
Cringe?

### CODE REVIEW

**Comment by Bobthe28th** [comment]
wait there is a new marker entity I might be able to use that instead of armor stand

**Comment by Bobthe28th** [comment]
> wait there is a new marker entity I might be able to use that instead of armor stand

marker cannot have equipment

**Comment by Bobthe28th** [comment]
@Tman2143 do you think it looks good? rotation is kinda funky sometimes but works 50% of the time, it glows banner color.

**Comment by Tman2143** [comment]
looks good but idk if i want banner to glow bc it will just stop glowing when on the ground

**Comment by Tman2143** [comment]
inconsistency

**Comment by Bobthe28th** [comment]
do you want me to make it glow on the ground? @Tman2143 
also I accidentally committed the custom damager thing to this branch

**Comment by Bobthe28th** [comment]
> looks good but idk if i want banner to glow bc it will just stop glowing when on the ground

or not glow on head

**Comment by Bobthe28th** [comment]
Imma merge, you can change it by making a pull request (make new branch don't commit to main) and change glowing from true to false in ctfplayer

**Comment by Bobthe28th** [comment]
https://github.com/Bobthe28th/CaptureTheFart/blob/020fb67cd01c3ced6e42cb9ffc51888ee0c13898/src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java#L102

**Comment by Tman2143** [comment]
just make flag never glow i think is the play

**Comment by Bobthe28th** [comment]
> you can change it by making a pull request (make new branch don't commit to main) and change glowing from true to false in ctfplayer
https://github.com/Bobthe28th/CaptureTheFart/blob/020fb67cd01c3ced6e42cb9ffc51888ee0c13898/src/me/bobthe28th/capturethefart/ctf/CTFPlayer.java#L102

@Tman2143 Then make a pull request

**Comment by Tman2143** [comment]
my phone tho it's so hard to change that on da phone doe

**Pull request merged**
