### PR TITLE
Halfs demolitionists self knockback with TNT

### PR DESCRIPTION
**Pull request by Bobthe28th**
Sets div from 1 to 2

### CODE REVIEW

**Comment by Bobthe28th** [comment]
I dont know how much knockback it SHOULD do and I don't know if it should do teammate knockback.

**Comment by Bobthe28th** [comment]
Consider this to close #38

**Comment by Bobthe28th** [comment]
@Tman2143 is 1/2 knockback (of what it was before) too much or too little? It should go down a certain amount as before it was way to much

**Comment by Bobthe28th** [comment]
> Consider this to close #38

#38 was closed as nothing was to change

**Comment by Tman2143** [comment]
maybe

**Comment by Tman2143** [comment]
try 1.5

**Comment by Bobthe28th** [comment]
> try 1.5

The value is the divider, before it was 1 so it wasn't doing anything. In this pr it sets it to 2, halfing the knockback so setting it to 1.5 is higher knockback than 2

**Comment by Bobthe28th** [comment]
I'll test both once I get back tonight

**Pull request merged**
